version: "3.3"

networks:
  fe-nw:
    driver: bridge
    ipam:
      config:
        - subnet: ${FE_SUBNET}
  be-nw:
  db:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    env_file:
      - ./env/dev/db.env
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    expose:
      - ${MYSQL_CONTAINER_PORT}
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - db

  fe_lb:
    image: nginx:1.17.0
    container_name: fe-loadbalancer
    restart: always
    volumes:
      - ./env/dev/fe-nginx.conf:/etc/nginx/nginx.conf
    expose:
      - ${FE_CONTAINER_PORT}
    ports:
      - "${FE_CONTAINER_PORT}:${FE_CONTAINER_PORT}"
    networks:
      fe-nw:
        ipv4_address: ${FE_LB_IP}

  be_lb:
    image: nginx:1.17.0
    container_name: be-loadbalancer
    restart: always
    volumes:
      - ./env/dev/be-nginx.conf:/etc/nginx/nginx.conf
    expose:
      - ${BE_CONTAINER_PORT}
    ports:
      - "${BE_CONTAINER_PORT}:${BE_CONTAINER_PORT}"
    networks:
      fe-nw:
        ipv4_address: ${BE_LB_IP}
      be-nw:

  frontend:
    build:
      context: ./dockerfiles/frontend/
      dockerfile: ./Dockerfile
      args:
        be_loadbalancer_ip: ${BE_LB_IP}
    restart: always
    expose:
      - ${FE_CONTAINER_PORT}
    links:
      - be_lb:be_lb
    networks:
      - fe-nw

  backend:
    build:
      context: ./dockerfiles/backend/
      dockerfile: ./Dockerfile
    restart: always
    expose:
      - ${BE_CONTAINER_PORT}
    depends_on:
      - mysql
    networks:
      - be-nw
      - db

#  jenkins:
#    image: jenkins/jenkins:2.179-alpine
#    restart: always

volumes:
  mysql-db:






