#============================================
#       Configs for Amazon Web Services:
#============================================

#Datasourse props
spring:
  datasource:
    url: jdbc:mysql://bike.c3uagfrtrhvd.us-east-2.rds.amazonaws.com:3306/bike_championship?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: rootpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect

#Jwt properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

server:
  port: 5000

#Cors constants
cors:
  origin: "http://bike-championship.s3-website.us-east-2.amazonaws.com"