#============================================
#          Configs for Docker:
#============================================

#Datasourse props
spring:
  AllowPublicKeyRetrieval:
  datasource:
    url: jdbc:mysql://192.168.1.37:3306/bike_championship?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

#Jwt properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

#Cors constants
cors:
  origin: "*"
